<?php

declare(strict_types=1);

/** @var array<string, mixed> $report */
$summary     = $report['summary'];
$timeBuckets = $summary['time_buckets'] ?? [];
$testName    = $report['meta']['test_name'] ?? null;

$esc = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');

// Build labels and per-percentile datasets
$labels   = [];
$p50s     = [];
$p75s     = [];
$p95s     = [];
$p99s     = [];
$avgMs    = [];

// Collect all latency distribution bin labels from first non-empty bucket
$binLabels = [];
foreach ($timeBuckets as $bucket) {
    if (isset($bucket['latency_dist']) && is_array($bucket['latency_dist']) && $bucket['latency_dist'] !== []) {
        foreach ($bucket['latency_dist'] as $bin) {
            $binLabels[] = (string) $bin['label'];
        }
        break;
    }
}

// Per-bin stacked data: indexed by bin index → list of counts per time bucket
/** @var array<int, list<int>> $binData */
$binData = [];
foreach ($timeBuckets as $bucket) {
    $labels[] = 't=' . (string) (int) ($bucket['t'] ?? 0) . 's';
    $p50s[]   = (float) ($bucket['p50'] ?? 0.0);
    $p75s[]   = (float) ($bucket['p75'] ?? 0.0);
    $p95s[]   = (float) ($bucket['p95'] ?? 0.0);
    $p99s[]   = (float) ($bucket['p99'] ?? 0.0);
    $avgMs[]  = (float) ($bucket['avg_latency_ms'] ?? 0.0);

    $dist = is_array($bucket['latency_dist'] ?? null) ? $bucket['latency_dist'] : [];
    foreach ($dist as $i => $bin) {
        $binData[$i][] = (int) ($bin['count'] ?? 0);
    }
}

// Chart.js color palette for bins (warm gradient)
$binColors = [
    'rgba(99,102,241,0.75)',
    'rgba(59,130,246,0.75)',
    'rgba(6,182,212,0.75)',
    'rgba(16,185,129,0.75)',
    'rgba(245,158,11,0.75)',
    'rgba(249,115,22,0.75)',
    'rgba(239,68,68,0.75)',
    'rgba(139,92,246,0.75)',
];

$jsonLabels = (string) json_encode($labels, JSON_THROW_ON_ERROR);
$jsonP50    = (string) json_encode($p50s, JSON_THROW_ON_ERROR);
$jsonP75    = (string) json_encode($p75s, JSON_THROW_ON_ERROR);
$jsonP95    = (string) json_encode($p95s, JSON_THROW_ON_ERROR);
$jsonP99    = (string) json_encode($p99s, JSON_THROW_ON_ERROR);
$jsonAvg    = (string) json_encode($avgMs, JSON_THROW_ON_ERROR);

// Build stacked bar datasets JSON
$stackedDatasets = [];
foreach ($binLabels as $i => $binLabel) {
    $stackedDatasets[] = [
        'label' => $binLabel,
        'data' => $binData[$i] ?? [],
        'backgroundColor' => $binColors[$i % count($binColors)],
        'stack' => 'dist',
    ];
}
$jsonStacked = (string) json_encode($stackedDatasets, JSON_THROW_ON_ERROR);

$hasData = $labels !== [];
?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>eleload heatmap</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>
</head>
<body class="bg-gray-50 text-gray-800 antialiased" style="font-family:'IBM Plex Sans','Hiragino Sans','Yu Gothic',sans-serif">
<main class="max-w-5xl mx-auto px-4 py-8 space-y-6">

  <div class="flex items-start justify-between">
    <div>
      <h1 class="text-2xl font-bold tracking-tight text-gray-900">eleload heatmap report</h1>
      <?php if (is_string($testName) && $testName !== ''): ?>
        <p class="mt-1 text-sm text-gray-500"><?= $esc($testName) ?></p>
      <?php endif; ?>
    </div>
    <span class="text-xs text-gray-400 mt-1">v<?= $esc($report['meta']['version']) ?></span>
  </div>

  <?php if (!$hasData): ?>
  <div class="bg-white border border-gray-200 rounded-lg p-6 text-center text-gray-400 text-sm">
    No time-series data available. Re-run with <code class="font-mono">--duration</code> to generate per-second buckets.
  </div>
  <?php else: ?>

  <!-- Percentile time-series -->
  <div class="bg-white border border-gray-200 rounded-lg p-5">
    <h2 class="text-sm font-semibold text-gray-700 mb-4">Latency percentiles over time</h2>
    <canvas id="chartPercentiles" height="120"></canvas>
  </div>

  <!-- Latency distribution heatmap (stacked bar) -->
  <div class="bg-white border border-gray-200 rounded-lg p-5">
    <h2 class="text-sm font-semibold text-gray-700 mb-1">Latency distribution heatmap (requests per bin per second)</h2>
    <p class="text-xs text-gray-400 mb-4">Each bar = 1 s bucket. Stacked by latency range.</p>
    <canvas id="chartHeatmap" height="120"></canvas>
  </div>

  <?php endif; ?>

  <p class="text-xs text-gray-400 text-right">Generated by eleload <?= $esc($report['meta']['version']) ?></p>
</main>

<?php if ($hasData): ?>
<script>
(function () {
  'use strict';
  const GRID = 'rgba(0,0,0,0.05)';
  const base = {
    responsive: true,
    plugins: { legend: { labels: { boxWidth: 12, font: { size: 10 } } } },
    scales: {
      x: { grid: { color: GRID }, ticks: { font: { size: 10 }, maxTicksLimit: 20 } },
      y: { grid: { color: GRID }, ticks: { font: { size: 10 } }, beginAtZero: true },
    },
  };

  // Percentile line chart
  new Chart(document.getElementById('chartPercentiles'), {
    type: 'line',
    data: {
      labels: <?= $jsonLabels ?>,
      datasets: [
        { label: 'p50',  data: <?= $jsonP50 ?>, borderColor: '#10b981', backgroundColor: 'rgba(16,185,129,0)',  tension: 0.3, pointRadius: 0, borderWidth: 1.5 },
        { label: 'p75',  data: <?= $jsonP75 ?>, borderColor: '#6366f1', backgroundColor: 'rgba(99,102,241,0)',  tension: 0.3, pointRadius: 0, borderWidth: 1.5 },
        { label: 'p95',  data: <?= $jsonP95 ?>, borderColor: '#f59e0b', backgroundColor: 'rgba(245,158,11,0)',  tension: 0.3, pointRadius: 0, borderWidth: 2 },
        { label: 'p99',  data: <?= $jsonP99 ?>, borderColor: '#ef4444', backgroundColor: 'rgba(239,68,68,0)',   tension: 0.3, pointRadius: 0, borderWidth: 2 },
        { label: 'avg',  data: <?= $jsonAvg ?>, borderColor: '#94a3b8', backgroundColor: 'rgba(148,163,184,0.1)', tension: 0.3, pointRadius: 0, borderWidth: 1, borderDash: [4,2] },
      ],
    },
    options: {
      ...base,
      scales: {
        ...base.scales,
        x: { ...base.scales.x, title: { display: true, text: 'elapsed (s)', font: { size: 10 } } },
        y: { ...base.scales.y, title: { display: true, text: 'latency (ms)', font: { size: 10 } } },
      },
    },
  });

  // Stacked heatmap bar chart
  new Chart(document.getElementById('chartHeatmap'), {
    type: 'bar',
    data: {
      labels: <?= $jsonLabels ?>,
      datasets: <?= $jsonStacked ?>,
    },
    options: {
      ...base,
      plugins: { ...base.plugins, tooltip: { mode: 'index' } },
      scales: {
        ...base.scales,
        x: { ...base.scales.x, stacked: true, title: { display: true, text: 'elapsed (s)', font: { size: 10 } } },
        y: { ...base.scales.y, stacked: true, title: { display: true, text: 'requests', font: { size: 10 } } },
      },
    },
  });
}());
</script>
<?php endif; ?>
</body>
</html>
